

BERT:
  model:
    name_or_path: '../bert-large-cased'
    seqeval_path: 'seqeval.py'
    patience: 40

tri-train:
  preprocess:
    path: '../../data/CoNLLEN/tsv'
    gen_path: '../gpt2'
    seed: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
    split: [50]
  tritraining:
    episodes: 20
  model:
    name_or_path: '../bert-large-cased/'
    seqeval_path: 'seqeval.py'
